### ISSUE TITLE
Spelling error in meta tag

### ISSUE THREAD

**Issue by Lofty-Brambles** [aleksa-codes/astro-portfolio#38]
Just a new dev, I was exploring your blog for good meta tags to add. Noticed a spelling error with `creeator` here:
https://github.com/aleksa-codes/astro-portfolio/blob/9cab903348b3a1ca95bd2fd2e4b07a521b9f6989/src/components/SEO.astro#L83

**Comment by aleksa-codes** [comment]
> Just a new dev, I was exploring your blog for good meta tags to add. Noticed a spelling error with `creeator` here:
> 
> https://github.com/aleksa-codes/astro-portfolio/blob/9cab903348b3a1ca95bd2fd2e4b07a521b9f6989/src/components/SEO.astro#L83

Hi @Lofty-Brambles, thank you for finding this error. If you want to make a pull request for this, as practice, please feel free to do so.
